---
- hosts: all
  become: true
  tasks:
    - name: Install Git Package # Installation des paquets nécessaires
      apt:
        name: git
        state: present
        update_cache: yes
    - name: Install Apache2 package
      apt: name=apache2 update_cache=yes state=latest

    - name: Change Apache port # Changement du port d'écoute d'Apache2
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: "^Listen"
        line: "Listen 8080"

    - name: Change VirtualHost port # Changement du port dans la configuration du VHost
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: "^<VirtualHost"
        line: "<VirtualHost *:8080>"

    - name: Remove default website # Suppression des fichiers HTML par défaut
      file:
        path: /var/www/html
        state: absent

    - name: Clone website # Dépoiement du site depuis un repository GitHub
      git:
        repo: https://github.com/cloudacademy/static-website-example
        dest: /var/www/html

    - name: Restart Apache # Redémarrage du service Apache2
      service:
        name: apache2
        state: restarted
