name: Build Apache AMI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Clone Packer template repository
        run: git clone https://github.com/Hydrocarbure-H/TerrActions ./repo

      - name: Setup Packer
        uses: hashicorp/setup-packer@latest
        with:
          packer-version: "1.7.0"

      - name: Validate Packer Template
        run: packer validate ./repo/apache-packer.pkr.hcl

      - name: Build AMI with Packer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APP_NAME: "TerrAction"
          HTTPD_PORT: "8080"
        run: packer build -var 'app_name=${{ env.APP_NAME }}' -var 'httpd_port=${{ env.HTTPD_PORT }}' ./repo/apache-packer.pkr.hcl
